### PR TITLE
Remove Rawgit Dependencies

### PR DESCRIPTION
**Pull request by ethanaobrien**
Removes [rawgit](https://rawgit.com/ ) dependencies, because the site is going to be taken down. 

Must be hosted on web server, but works offline.

Is my Pull Request cleaner now?

### CODE REVIEW

**Comment by takahirox** [comment]
Thanks, yes it's cleaner now.

And sorry maybe I couldn't explain well in https://github.com/takahirox/MMDLoader-app/pull/4#issuecomment-832862493

https://rawgit.com ended and someone started an alternate CDN server https://raw.githack.com/ so you can just replace rawgit.com with raw.githack.com.

And if you encounter any problems with raw.githack.com for example CORS error, we may seek other CDN server like https://cdnjs.com/libraries/three.js/87

BTW you seemed to edit everything on browser. How did you test to check that the application keeps working with the changes?

**Comment by ethanaobrien** [comment]
I downloaded the repository as a zip, and then just re-uploaded all of the files once I had everything working!

I will do the conversion to raw.githack.com but chances are it will happen tomorrow. I'm kinda trying to do something else at the moment.

Thank you!

**Comment by takahirox** [comment]
I see, makes sense, thanks!

**Comment by ethanaobrien** [comment]
@takahirox I have successfully done everything. It is ready to merge

**Comment by ethanaobrien** [comment]
@takahirox Its been about a week. I'm @ ing you to make sure that you have gotten the message

**Comment by takahirox** [comment]
Thanks for pinging me.

It seems you have removed some `assets/vmd` and ` assets/vpd` files but please don't do that.

**Comment by ethanaobrien** [comment]
@takahirox Sorry about that. I did not realize that I had done that. I have fixed it!

**Comment by takahirox** [comment]
Thanks so much!

**Comment by ethanaobrien** [comment]
No Problem!

**Pull request merged**
