### PR TITLE
Remove rawgit dependencies.

### PR DESCRIPTION
**Pull request by ethanaobrien**
Removes [rawgit](https://rawgit.com/ ) dependencies, because the site is going to be taken down. Must be hosted on web server, but works offline.

### CODE REVIEW

**Comment by takahirox** [comment]
Good catch, thanks! But I prefer using https://raw.githack.com/ so far. And I would be pleased if you squash the commits.

**Comment by ethanaobrien** [comment]
Just a question, when you say to squash the commits does this mean to just undo everything and convert to https://raw.githack.com/ links? I'm willing to do it I am just need clarification first.

**Comment by takahirox** [comment]
"Squash the commits" means combining multiple commits into one or some in this case because currently this PR seems to have a tons of commits and most of them don't make sense like Create a and Delete a.

**Comment by ethanaobrien** [comment]
@takahirox Ok, I understand now. I am new to pull requests and things like that, how would I do this?

**Comment by takahirox** [comment]
After squashing you can force to push with "git push -f". Regarding how to squash, please google it or read Git manual.

**Comment by ethanaobrien** [comment]
@takahirox 
I dont use git, I can only access through the web browser (Because I am on chrome os). All the add and remove a was me creating a directory because it is the only way you can do so through the web browser. 

I am very sorry about this. I didnt mean for it to get so messy!

**Comment by ethanaobrien** [comment]
I am going to close this and try again. Sorry

**Comment by takahirox** [comment]
Yeah probably it would be good to make a new PR. Thanks.

**Pull request closed without merging**
